import plumberChatWidget from './the-tool-plumbers-use-to-book-jobs-while-they-sleep.html?raw';
import whyPlumbersLoseJobsMidCall from './why-plumbers-lose-jobs-mid-call.html?raw';
import hvacToolToBookMoreServiceCalls from './hvac-tool-to-book-more-service-calls.html?raw';
import rooferToolToCaptureStormLeads from './roofer-tool-to-capture-storm-leads.html?raw';
import electricianToolToBookMoreJobs from './electrician-tool-to-book-more-jobs.html?raw';
import restaurantQrCodeLoyaltySystem from './restaurant-qr-code-loyalty-system.html?raw';
import pestControlToolToBookMoreJobs from './pest-control-tool-to-book-more-jobs.html?raw';
import lawnCareToolToBookMoreCustomers from './lawn-care-tool-to-book-more-customers.html?raw';
import garageDoorRepairToolToBookMoreJobs from './garage-door-repair-tool-to-book-more-jobs.html?raw';
import howMuchMissedCallsCostServiceBusiness from './how-much-missed-calls-cost-service-business.html?raw';
import leadResponseTimeWhySpeedWinsTheJob from './lead-response-time-why-speed-wins-the-job.html?raw';
import autoRepairShopToolToBookMoreJobs from './auto-repair-shop-tool-to-book-more-jobs.html?raw';
import howToGetMoreGoogleReviewsServiceBusiness from './how-to-get-more-google-reviews-service-business.html?raw';
import whatToTextCustomerAfterJobToGet5StarReview from './what-to-text-customer-after-job-to-get-5-star-review.html?raw';
import whyCustomersDontLeaveVoicemailsAnymore from './why-customers-dont-leave-voicemails-anymore.html?raw';
import completeGuideAiAutomationLocalServiceBusinesses from './complete-guide-ai-automation-local-service-businesses.html?raw';
import locksmithAiToolToBookMoreJobs from './locksmith-ai-tool-to-book-more-jobs.html?raw';
import cleaningServiceAiToolToBookMoreClients from './cleaning-service-ai-tool-to-book-more-clients.html?raw';
import aiVsHiringReceptionistServiceBusiness from './ai-vs-hiring-receptionist-service-business.html?raw';
import googleBusinessProfileMoreImportantThanWebsite from './google-business-profile-more-important-than-website.html?raw';
import pressureWashingAiToolToBookMoreJobs from './pressure-washing-ai-tool-to-book-more-jobs.html?raw';
import howToRespondToNegativeGoogleReviewsServiceBusiness from './how-to-respond-to-negative-google-reviews-service-business.html?raw';
import howServiceBusinessesStayBusyInSlowSeason from './how-service-businesses-stay-busy-in-slow-season.html?raw';
import howMuchShouldServiceBusinessSpendOnMarketing from './how-much-should-service-business-spend-on-marketing.html?raw';
import whyServiceBusinessLeadsGoCold from './why-service-business-leads-go-cold.html?raw';
import treeServiceBusinessStopLosingLeads from './tree-service-business-stop-losing-leads.html?raw';
import aboutPageThatConvertsServiceBusiness from './about-page-that-converts-service-business.html?raw';
import howToGetMoreReferralsServiceBusiness from './how-to-get-more-referrals-service-business.html?raw';
import poolServiceAiToolToBookMoreJobs from './pool-service-ai-tool-to-book-more-jobs.html?raw';
import handymanAiToolToBookMoreJobs from './handyman-ai-tool-to-book-more-jobs.html?raw';
import paintingContractorAiToolToBookMoreJobs from './painting-contractor-ai-tool-to-book-more-jobs.html?raw';
import howToPriceHomeServiceBusiness from './how-to-price-home-service-business.html?raw';
import whatIsCrmServiceBusiness from './what-is-crm-service-business.html?raw';
import windowCleaningAiToolToBookMoreJobs from './window-cleaning-ai-tool-to-book-more-jobs.html?raw';
import flooringContractorAiToolToBookMoreJobs from './flooring-contractor-ai-tool-to-book-more-jobs.html?raw';
import hvacTuneUpSeasonLeads from './hvac-tune-up-season-leads.html?raw';
import howToGetRepeatCustomersServiceBusiness from './how-to-get-repeat-customers-service-business.html?raw';
import howToDifferentiateYourServiceBusiness from './how-to-differentiate-your-service-business.html?raw';
import howToSetUpMissedCallTextBack from './how-to-set-up-missed-call-text-back.html?raw';
import howToAutomateGoogleReviewRequests from './how-to-automate-google-review-requests.html?raw';
import howToBuildLeadFollowUpSequence from './how-to-build-lead-follow-up-sequence.html?raw';
import howToAddOnlineBookingServiceBusiness from './how-to-add-online-booking-service-business.html?raw';
import howToSetUpAppointmentReminders from './how-to-set-up-appointment-reminders.html?raw';
import howToFollowUpAfterEstimate from './how-to-follow-up-after-estimate.html?raw';
import howToBuildReferralProgramServiceBusiness from './how-to-build-referral-program-service-business.html?raw';
import howToWriteServiceGuarantee from './how-to-write-service-guarantee.html?raw';
import howToTrackLeadsServiceBusiness from './how-to-track-leads-service-business.html?raw';
import howToHandlePriceObjections from './how-to-handle-price-objections.html?raw';
import howAiBooksAppointmentsServiceBusiness from './how-ai-books-appointments-service-business.html?raw';
import whatYouNeedToBuildAnAiReceptionistServiceBusiness from './what-you-need-to-build-an-ai-receptionist-service-business.html?raw';
import doYouNeedACrmServiceBusiness from './do-you-need-a-crm-service-business.html?raw';
import howToReactivateOldCustomers from './how-to-reactivate-old-customers.html?raw';
import whatYourWebsiteNeedsBeforeYouRunAds from './what-your-website-needs-before-you-run-ads.html?raw';
import fenceInstallationBusinessBookMoreJobs from './fence-installation-business-book-more-jobs.html?raw';
import gutterCleaningBusinessBookMoreJobs from './gutter-cleaning-business-book-more-jobs.html?raw';
import applianceRepairShopBookMoreJobs from './appliance-repair-shop-book-more-jobs.html?raw';
import howToTurnOneTimeCustomersIntoRecurringRevenue from './how-to-turn-one-time-customers-into-recurring-revenue.html?raw';
import whatToSayWhenCustomerSaysIllThinkAboutIt from './what-to-say-when-customer-says-ill-think-about-it.html?raw';

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  author: string;
  date: string;
  tags: string[];
  featuredImage?: string;
  metaTitle?: string;
  content: string;
}

export const posts: BlogPost[] = [
  {
    slug: 'the-tool-plumbers-use-to-book-jobs-while-they-sleep',
    title: 'The One Tool Plumbers Are Quietly Adding to Their Websites That Books Jobs While They Sleep',
    description: 'Discover the AI webchat tool top plumbers are adding to their websites to capture leads 24/7 and book jobs automatically — even at 2am.',
    metaTitle: 'The Tool Plumbers Use to Book Jobs While They Sleep | Wayne AI',
    author: 'Wayne AI',
    date: '2025-03-15',
    tags: ['plumbing', 'lead generation', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=1200&auto=format&fit=crop&q=80',
    content: plumberChatWidget,
  },
  {
    slug: 'why-plumbers-lose-jobs-mid-call',
    title: 'Why Plumbers Lose Jobs While They\'re on a Job (And the Fix That Runs Itself)',
    description: 'Most plumbers miss 5+ calls a week without realizing it — because they\'re physically unable to answer mid-repair. Here\'s what those missed calls are actually costing you and how a simple text-back fixes it.',
    metaTitle: 'Why Plumbers Lose Jobs Mid-Call (And How to Fix It) | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['plumbing', 'missed calls', 'lead response', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&auto=format&fit=crop&q=80',
    content: whyPlumbersLoseJobsMidCall,
  },
  {
    slug: 'hvac-tool-to-book-more-service-calls',
    title: "The Tool HVAC Companies Are Using to Book More Service Calls Without Answering Every Phone",
    description: "Discover how smart HVAC companies are using AI to respond to leads instantly, book service calls automatically, and stop losing jobs to competitors who pick up faster.",
    metaTitle: "The Tool HVAC Companies Use to Book More Service Calls | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-03',
    tags: ["HVAC","lead generation","automation"],
    featuredImage: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1200&auto=format&fit=crop&q=80',
    content: hvacToolToBookMoreServiceCalls,
  },
  {
    slug: 'roofer-tool-to-capture-storm-leads',
    title: "The Tool Roofers Are Using to Capture Storm Leads Before the Competition Gets There",
    description: "When a storm rolls through, every roofer in town is chasing the same leads. Discover how smart roofing companies are using AI to respond first, book inspections automatically, and close more jobs during peak season.",
    metaTitle: "The Tool Roofers Use to Capture Storm Leads First | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["roofing","lead generation","automation"],
    featuredImage: 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=1200&auto=format&fit=crop&q=80',
    content: rooferToolToCaptureStormLeads,
  },
  {
    slug: 'electrician-tool-to-book-more-jobs',
    title: "The Tool Electricians Are Using to Book More Jobs Without Playing Phone Tag All Day",
    description: "Every missed call is a job that went to another electrician. Discover how busy electrical contractors are using AI to respond instantly, book service calls automatically, and stop losing work to whoever picks up faster.",
    metaTitle: "The Tool Electricians Use to Book More Jobs | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["electrician","lead generation","automation"],
    featuredImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&auto=format&fit=crop&q=80',
    content: electricianToolToBookMoreJobs,
  },
  {
    slug: 'restaurant-qr-code-loyalty-system',
    title: "The QR Code Trick Restaurants Are Using to Turn One-Time Diners Into Regulars",
    description: "A QR code on the table, a free dessert offer, and suddenly your restaurant has a direct line to every customer who ever sat down. Here's how smart restaurants are using AI to turn one-time diners into loyal regulars.",
    metaTitle: "The QR Code Trick Restaurants Use to Build Loyal Regulars | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["restaurant","loyalty","automation"],
    featuredImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&auto=format&fit=crop&q=80',
    content: restaurantQrCodeLoyaltySystem,
  },
  {
    slug: 'pest-control-tool-to-book-more-jobs',
    title: "The Tool Pest Control Companies Are Using to Book More Jobs Without Losing Customers to the First Company That Responds",
    description: "When bugs show up, homeowners call every pest control company they can find and go with whoever responds first. Discover how smart pest control companies are using AI to respond instantly, book repeat service plans automatically, and stop losing seasonal spikes to competitors who simply pick up faster.",
    metaTitle: "The Tool Pest Control Companies Use to Book More Jobs | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["pest control","lead generation","automation"],
    content: pestControlToolToBookMoreJobs,
  },
  {
    slug: 'lawn-care-tool-to-book-more-customers',
    title: "The Tool Lawn Care Companies Are Using to Book More Customers Without Losing the Spring Rush",
    description: "Every spring, 50 homeowners call in one week and the companies that respond first fill their routes. Discover how smart lawn care businesses are using AI to capture every lead, lock in recurring customers, and stop losing jobs to whoever picks up faster.",
    metaTitle: "The Tool Lawn Care Companies Use to Book More Customers | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["lawn care","lead generation","automation"],
    content: lawnCareToolToBookMoreCustomers,
  },
  {
    slug: 'garage-door-repair-tool-to-book-more-jobs',
    title: "The Tool Garage Door Companies Are Using to Book More Jobs Without Missing a Single Urgent Call",
    description: "Broken springs don't wait for business hours. See how garage door repair companies are capturing every urgent call — even at 6am — and booking more high-ticket jobs automatically.",
    metaTitle: "The Tool Garage Door Companies Are Using to Book More Jobs | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["garage door","lead generation","automation"],
    content: garageDoorRepairToolToBookMoreJobs,
  },
  {
    slug: 'how-much-missed-calls-cost-service-business',
    title: "How Much Are Missed Calls Actually Costing Your Service Business?",
    description: "Most service business owners think missed calls are a minor inconvenience. The math says otherwise. Here's what unanswered phones are really costing you.",
    metaTitle: "How Much Do Missed Calls Cost a Service Business? | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["lead generation","missed calls","revenue"],
    content: howMuchMissedCallsCostServiceBusiness,
  },
  {
    slug: 'lead-response-time-why-speed-wins-the-job',
    title: "The 5-Minute Lead Response Rule: Why Speed Wins or Loses the Job",
    description: "Leads contacted within 5 minutes are 9x more likely to convert. Here's why response speed is the single biggest factor in whether local service businesses win or lose jobs — and what to do about it.",
    metaTitle: "The 5-Minute Lead Response Rule: Why Speed Wins or Loses the Job | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["lead generation","response time","automation"],
    content: leadResponseTimeWhySpeedWinsTheJob,
  },
  {
    slug: 'auto-repair-shop-tool-to-book-more-jobs',
    title: "Why Auto Repair Shops Lose Jobs Every Time They Miss a Call",
    description: "Independent auto repair shops lose hundreds of dollars in revenue every time a call goes unanswered. Here's how AI-powered instant text response fills your bays without hiring more staff.",
    metaTitle: "Auto Repair Shop Tool to Book More Jobs | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["auto repair","lead generation","automation"],
    content: autoRepairShopToolToBookMoreJobs,
  },
  {
    slug: 'how-to-get-more-google-reviews-service-business',
    title: "How to Get More Google Reviews for Your Service Business (Without Begging)",
    description: "Most satisfied customers never leave reviews — they just move on. Here's the exact system local service businesses use to collect more Google reviews automatically, every time.",
    metaTitle: "How to Get More Google Reviews for Your Service Business | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["google reviews","reputation","local SEO"],
    content: howToGetMoreGoogleReviewsServiceBusiness,
  },
  {
    slug: 'what-to-text-customer-after-job-to-get-5-star-review',
    title: "What to Text a Customer After a Job to Get a 5-Star Review",
    description: "Most service businesses leave reviews on the table because no one follows up. Here are 3 real text templates you can send today — plus how to automate the whole thing so you never forget.",
    metaTitle: "What to Text a Customer After a Job to Get a 5-Star Review | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["google reviews","reputation","customer follow-up"],
    content: whatToTextCustomerAfterJobToGet5StarReview,
  },
  {
    slug: 'why-customers-dont-leave-voicemails-anymore',
    title: "Why Customers Don't Leave Voicemails Anymore (And What That's Costing You)",
    description: "If you're counting on voicemail to catch the leads you miss, you're losing jobs every day. Here's the hard truth about how customer behavior has changed — and what actually works now.",
    metaTitle: "Why Customers Don't Leave Voicemails Anymore | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["lead generation","missed calls","customer behavior"],
    content: whyCustomersDontLeaveVoicemailsAnymore,
  },
  {
    slug: 'complete-guide-ai-automation-local-service-businesses',
    title: "The Complete Guide to AI Automation for Local Service Businesses",
    description: "A comprehensive guide to AI automation for local service businesses — covering missed call recovery, instant lead response, appointment reminders, and review generation. Learn how plumbers, HVAC techs, roofers, electricians, and more are using simple automation to book more jobs without hiring more staff.",
    metaTitle: "The Complete Guide to AI Automation for Local Service Businesses | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["AI automation","local service business","lead generation","guide"],
    content: completeGuideAiAutomationLocalServiceBusinesses,
  },
  {
    slug: 'locksmith-ai-tool-to-book-more-jobs',
    title: "The Tool Locksmiths Are Using to Book More Emergency Jobs Without Answering Every Call",
    description: "Locksmiths lose emergency jobs every day to a single missed call. Here's how automated text-back and lead response tools are helping independent locksmiths capture after-hours revenue without hiring more staff.",
    metaTitle: "AI Tool Locksmiths Use to Book More Emergency Jobs | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["locksmith", "AI automation", "missed calls", "lead response"],
    featuredImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&auto=format&fit=crop&q=80",
    content: locksmithAiToolToBookMoreJobs,
  },
  {
    slug: 'cleaning-service-ai-tool-to-book-more-clients',
    title: "How Cleaning Services Are Filling Their Schedules Faster With AI Lead Response",
    description: "If your cleaning business isn't responding to leads within minutes, you're losing recurring clients worth thousands of dollars a year. Here's how AI-powered lead response is changing the game for small cleaning companies.",
    metaTitle: "How Cleaning Services Fill Their Schedules Faster With AI Lead Response | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["cleaning service", "AI automation", "lead response", "recurring revenue"],
    featuredImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&auto=format&fit=crop&q=80",
    content: cleaningServiceAiToolToBookMoreClients,
  },
  {
    slug: 'ai-vs-hiring-receptionist-service-business',
    title: "AI vs. Hiring a Receptionist: What Actually Makes Sense for a Service Business",
    description: "Thinking about hiring a receptionist for your service business? Before you post that job listing, run the real numbers — and see where AI automation outperforms a full-time hire, and where it doesn't.",
    metaTitle: "AI vs. Hiring a Receptionist for a Service Business | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["AI automation", "receptionist", "service business", "cost comparison"],
    featuredImage: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&auto=format&fit=crop&q=80",
    content: aiVsHiringReceptionistServiceBusiness,
  },
  {
    slug: 'google-business-profile-more-important-than-website',
    title: "Why Your Google Business Profile Matters More Than Your Website",
    description: "Most local service business owners are pouring money into websites while ignoring the one thing that actually drives calls — their Google Business Profile. Here's why GBP matters more, and what to do about it.",
    metaTitle: "Why Your Google Business Profile Matters More Than Your Website | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["Google Business Profile", "local SEO", "service business", "Google Maps"],
    featuredImage: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=1200&auto=format&fit=crop&q=80",
    content: googleBusinessProfileMoreImportantThanWebsite,
  },
  {
    slug: 'pressure-washing-ai-tool-to-book-more-jobs',
    title: "How Pressure Washing Companies Are Booking More Jobs Without Playing Phone Tag",
    description: "Spring is the make-or-break season for pressure washing companies. Learn how AI-powered missed call text-back and lead automation help owner-operators capture more jobs without stopping work to answer the phone.",
    metaTitle: "How Pressure Washing Companies Book More Jobs With AI Automation | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["pressure washing", "AI automation", "missed calls", "seasonal"],
    featuredImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80",
    content: pressureWashingAiToolToBookMoreJobs,
  },
  {
    slug: 'how-to-respond-to-negative-google-reviews-service-business',
    title: "How to Respond to Negative Google Reviews (Without Making It Worse)",
    description: "A 1-star review just landed on your Google profile. Here's exactly how local service businesses should respond — with templates, rules, and the long-game strategy that actually protects your reputation.",
    metaTitle: "How to Respond to Negative Google Reviews (Service Business Guide) | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["Google reviews", "reputation management", "service business", "customer service"],
    featuredImage: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&auto=format&fit=crop&q=80",
    content: howToRespondToNegativeGoogleReviewsServiceBusiness,
  },
  {
    slug: 'how-service-businesses-stay-busy-in-slow-season',
    title: "How to Keep Your Service Business Busy When the Slow Season Hits",
    description: "The slow season is real — but the businesses that stay busiest aren't just luckier. They built systems during the peak. Here are five tactics local service businesses can use right now to fill the calendar back up.",
    metaTitle: "How to Keep Your Service Business Busy in the Slow Season | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["slow season", "service business", "marketing", "customer reactivation"],
    featuredImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&auto=format&fit=crop&q=80",
    content: howServiceBusinessesStayBusyInSlowSeason,
  },
  {
    slug: 'how-much-should-service-business-spend-on-marketing',
    title: "How Much Should a Local Service Business Spend on Marketing?",
    description: "Real numbers, honest benchmarks, and a practical breakdown of how local service businesses should allocate their marketing budget — from $1,500/month to $5,000/month.",
    metaTitle: "How Much Should a Local Service Business Spend on Marketing? | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["marketing budget", "service business", "local marketing", "ROI"],
    featuredImage: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&auto=format&fit=crop&q=80",
    content: howMuchShouldServiceBusinessSpendOnMarketing,
  },
  {
    slug: 'why-service-business-leads-go-cold',
    title: 'The 3-Day Window: Why Most Service Business Leads Go Cold and Never Come Back',
    description: 'Most service business leads die within 24 hours — not because the customer lost interest, but because no one followed up fast enough. Here\'s exactly what happens and how to fix it.',
    metaTitle: 'Why Service Business Leads Go Cold (And How to Fix It) | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-02',
    tags: ['lead follow-up', 'service business', 'lead response', 'conversion'],
    featuredImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&auto=format&fit=crop&q=80',
    content: whyServiceBusinessLeadsGoCold,
  },
  {
    slug: 'tree-service-business-stop-losing-leads',
    title: "Why Tree Service Companies Lose Jobs Before They Even Know Someone Called",
    description: "Tree service companies lose high-value jobs every day — not because they're bad at the work, but because they can't answer the phone mid-job. Here's how AI automation fixes the missed call problem before it costs you another $1,500 removal.",
    metaTitle: "Why Tree Service Companies Lose Jobs Before They Even Know Someone Called | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-03',
    tags: ["tree service", "AI automation", "missed calls", "lead response"],
    featuredImage: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=1200&auto=format&fit=crop&q=80",
    content: treeServiceBusinessStopLosingLeads,
  },
  {
    slug: 'about-page-that-converts-service-business',
    title: 'Your "About Us" Page Is Losing You Customers. Here\'s How to Fix It.',
    description: "Most service business About pages are generic placeholders that kill trust instead of building it. Here's what to put on yours — and what to cut.",
    metaTitle: "How to Write an About Page That Converts | Service Business Website Tips",
    author: "Wayne AI",
    date: '2026-04-03',
    tags: ["website", "conversion", "service business", "about page"],
    featuredImage: "https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=1200&auto=format&fit=crop&q=80",
    content: aboutPageThatConvertsServiceBusiness,
  },
  {
    slug: 'how-to-get-more-referrals-service-business',
    title: "The Simplest Way to Get More Referrals From Customers Who Already Love You",
    description: "Referrals are the best leads you'll ever get — but they don't happen on their own. Here's how local service businesses can build a simple system to turn happy customers into a steady stream of warm referrals.",
    metaTitle: "How to Get More Referrals for Your Service Business | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-03',
    tags: ["referrals", "service business", "customer retention", "word of mouth"],
    featuredImage: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&auto=format&fit=crop&q=80",
    content: howToGetMoreReferralsServiceBusiness,
  },
  {
    slug: 'pool-service-ai-tool-to-book-more-jobs',
    title: 'Why Pool Service Companies Lose Leads After Hours (And How to Fix It)',
    description: 'Pool service companies miss most of their leads after hours. Here\'s why it happens and how AI automation helps you capture and book those jobs automatically.',
    metaTitle: 'Why Pool Service Companies Lose After-Hours Leads',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['pool service', 'AI automation', 'lead response', 'after hours'],
    featuredImage: 'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=1200&auto=format&fit=crop&q=80',
    content: poolServiceAiToolToBookMoreJobs,
  },
  {
    slug: 'handyman-ai-tool-to-book-more-jobs',
    title: 'How Handyman Businesses Book More Jobs Without Answering Every Call',
    description: 'Missed calls cost handyman businesses real jobs. Learn how AI automation handles lead capture, follow-up, and booking so you never lose work to voicemail again.',
    metaTitle: 'How Handyman Businesses Book More Jobs Without Every Call',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['handyman', 'AI automation', 'missed calls', 'lead response'],
    featuredImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&auto=format&fit=crop&q=80',
    content: handymanAiToolToBookMoreJobs,
  },
  {
    slug: 'painting-contractor-ai-tool-to-book-more-jobs',
    title: 'How Painting Contractors Stop Losing Bids to Faster Competitors',
    description: 'Painting contractors lose jobs every week to faster-responding competitors. Learn how AI automation closes that gap and keeps your calendar full.',
    metaTitle: 'How Painting Contractors Stop Losing Bids to Faster Rivals',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['painting contractor', 'AI automation', 'lead response', 'estimate booking'],
    featuredImage: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=1200&auto=format&fit=crop&q=80',
    content: paintingContractorAiToolToBookMoreJobs,
  },
  {
    slug: 'how-to-price-home-service-business',
    title: 'How to Price Your Home Service Business (Without Losing Jobs or Leaving Money on the Table)',
    description: 'Stop guessing at your prices. Learn the exact framework to calculate costs, research your market, and charge what you\'re worth without losing jobs.',
    metaTitle: 'How to Price Your Home Service Business Right',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['pricing', 'service business', 'profit margin', 'business advice'],
    featuredImage: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&auto=format&fit=crop&q=80',
    content: howToPriceHomeServiceBusiness,
  },
  {
    slug: 'what-is-crm-service-business',
    title: 'What Is a CRM and Does Your Service Business Actually Need One?',
    description: 'CRM stands for Customer Relationship Manager — but what does that mean for a plumber or HVAC tech? Here\'s what it does, and whether your business needs one.',
    metaTitle: 'What Is a CRM? Do Service Businesses Actually Need One?',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['CRM', 'service business', 'lead management', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&auto=format&fit=crop&q=80',
    content: whatIsCrmServiceBusiness,
  },
  {
    slug: 'window-cleaning-ai-tool-to-book-more-jobs',
    title: 'How Window Cleaning Companies Fill Their Schedule Every Spring Without Missing a Call',
    description: 'Missing calls during spring rush costs window cleaning companies real jobs. Here\'s how automated follow-up fills your schedule without adding staff.',
    metaTitle: 'How Window Cleaners Book More Jobs This Spring',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['window cleaning', 'AI automation', 'missed calls', 'spring season'],
    featuredImage: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=1200&auto=format&fit=crop&q=80',
    content: windowCleaningAiToolToBookMoreJobs,
  },
  {
    slug: 'flooring-contractor-ai-tool-to-book-more-jobs',
    title: 'How Flooring Contractors Win More Estimates Before the Competition Calls Back',
    description: 'Flooring contractors lose jobs to faster competitors every day. Learn how automated follow-up helps you capture leads before anyone else calls back.',
    metaTitle: 'How Flooring Contractors Win More Estimates & Jobs',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['flooring contractor', 'AI automation', 'lead response', 'estimates'],
    featuredImage: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=1200&auto=format&fit=crop&q=80',
    content: flooringContractorAiToolToBookMoreJobs,
  },
  {
    slug: 'hvac-tune-up-season-leads',
    title: 'Why HVAC Companies Lose Tune-Up Season Leads (And the Fix That Runs Itself)',
    description: 'Spring tune-up season floods your phone lines. Learn why HVAC companies miss so many leads and how automated follow-up captures every one.',
    metaTitle: 'Why HVAC Companies Lose Tune-Up Season Leads',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['HVAC', 'seasonal', 'AI automation', 'missed calls', 'tune-up'],
    featuredImage: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1200&auto=format&fit=crop&q=80',
    content: hvacTuneUpSeasonLeads,
  },
  {
    slug: 'how-to-get-repeat-customers-service-business',
    title: 'The Easiest Way to Get More Repeat Business From Customers You Already Have',
    description: 'Your best new customer is one you already have. Learn simple tactics and automation to win repeat business from customers who already trust you.',
    metaTitle: 'Get More Repeat Customers for Your Service Business',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['repeat customers', 'customer retention', 'service business', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&auto=format&fit=crop&q=80',
    content: howToGetRepeatCustomersServiceBusiness,
  },
  {
    slug: 'how-to-differentiate-your-service-business',
    title: 'How to Explain What Makes Your Business Different (Without Sounding Like Everyone Else)',
    description: 'Every competitor claims "licensed, insured, 5-star service." Learn how to find and communicate what actually makes your service business different.',
    metaTitle: 'How to Make Your Service Business Stand Out',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['marketing', 'differentiation', 'service business', 'positioning'],
    featuredImage: 'https://images.unsplash.com/photo-1664575602276-acd073f104c1?w=1200&auto=format&fit=crop&q=80',
    content: howToDifferentiateYourServiceBusiness,
  },
  {
    slug: 'how-to-set-up-missed-call-text-back',
    title: 'How to Set Up a Missed-Call Text-Back for Your Service Business (Step by Step)',
    description: 'A missed call doesn\'t have to mean a lost lead. Here\'s how to set up an automated text-back that responds in seconds — so you keep the conversation alive while you\'re on the job.',
    metaTitle: 'How to Set Up a Missed-Call Text-Back for Your Service Business | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['automation', 'lead generation', 'missed calls', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1534536281715-e28d76689b4d?w=1200&auto=format&fit=crop&q=80',
    content: howToSetUpMissedCallTextBack,
  },
  {
    slug: 'how-to-automate-google-review-requests',
    title: 'How to Automate Google Review Requests After Every Job (Without Asking Awkwardly in Person)',
    description: 'Stop relying on your techs to remember to ask. Here\'s how to build an automated review request that goes out at exactly the right moment — every time, without anyone lifting a finger.',
    metaTitle: 'How to Automate Google Review Requests for Your Service Business | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['reviews', 'automation', 'google', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&auto=format&fit=crop&q=80',
    content: howToAutomateGoogleReviewRequests,
  },
  {
    slug: 'how-to-build-lead-follow-up-sequence',
    title: 'How to Build a Lead Follow-Up Sequence That Books Jobs While You\'re on the Job',
    description: 'Most service business leads go cold because nobody followed up. Here\'s how to build a 5-touch automated sequence that stays on leads for a week — without you remembering to do a thing.',
    metaTitle: 'How to Build a Lead Follow-Up Sequence for Your Service Business | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['automation', 'lead generation', 'follow-up', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80',
    content: howToBuildLeadFollowUpSequence,
  },
  {
    slug: 'how-to-add-online-booking-service-business',
    title: 'How to Add Online Booking to Your Service Business Website (Without Hiring a Developer)',
    description: 'If customers can\'t book when they\'re ready, they\'ll find someone who lets them. Here\'s how to set up online booking for your service business — step by step, no developer needed.',
    metaTitle: 'How to Add Online Booking to Your Service Business Website | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['booking', 'automation', 'website', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&auto=format&fit=crop&q=80',
    content: howToAddOnlineBookingServiceBusiness,
  },
  {
    slug: 'how-to-set-up-appointment-reminders',
    title: 'How to Set Up Automated Appointment Reminders That Cut No-Shows (Step by Step)',
    description: 'No-shows cost you time, money, and a slot that could have been filled. Here\'s how to build an automated reminder sequence that confirms appointments and catches cancellations before your tech drives out.',
    metaTitle: 'How to Set Up Automated Appointment Reminders for Your Service Business | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['automation', 'appointments', 'no-shows', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&auto=format&fit=crop&q=80',
    content: howToSetUpAppointmentReminders,
  },
  {
    slug: 'how-to-follow-up-after-estimate',
    title: 'How to Write a Follow-Up After Giving an Estimate (With Templates)',
    description: 'Most estimates don\'t get rejected — they get forgotten. Here\'s how to follow up after sending a quote, what to say at each touch, and real templates you can copy today.',
    metaTitle: 'How to Follow Up After Giving an Estimate | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['sales', 'estimates', 'follow-up', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&auto=format&fit=crop&q=80',
    content: howToFollowUpAfterEstimate,
  },
  {
    slug: 'how-to-build-referral-program-service-business',
    title: 'How to Build a Simple Referral Program for Your Service Business (Without Software)',
    description: 'Referrals are your best leads — but most service businesses treat them as a happy accident. Here\'s how to build a simple referral program that runs on a clear ask, a good incentive, and one follow-up habit.',
    metaTitle: 'How to Build a Referral Program for Your Service Business | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['referrals', 'marketing', 'growth', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&auto=format&fit=crop&q=80',
    content: howToBuildReferralProgramServiceBusiness,
  },
  {
    slug: 'how-to-write-service-guarantee',
    title: 'How to Write a Service Guarantee That Wins Jobs (And What to Avoid)',
    description: '"Satisfaction guaranteed" means nothing. Here\'s how to write a specific, credible guarantee that actually builds trust with skeptical customers — and what to leave out.',
    metaTitle: 'How to Write a Service Guarantee That Wins Jobs | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['trust', 'marketing', 'conversion', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=1200&auto=format&fit=crop&q=80',
    content: howToWriteServiceGuarantee,
  },
  {
    slug: 'how-to-track-leads-service-business',
    title: 'How to Track Where Your Leads Are Coming From (Without a Marketing Degree)',
    description: 'Most service business owners spend money on marketing and have no idea which channel is actually sending jobs. Here\'s a simple system to find out — no analytics degree required.',
    metaTitle: 'How to Track Where Your Leads Come From | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['marketing', 'lead tracking', 'analytics', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80',
    content: howToTrackLeadsServiceBusiness,
  },
  {
    slug: 'how-to-handle-price-objections',
    title: 'How to Handle a Price Objection Without Lowering Your Price',
    description: '"I got a cheaper quote" doesn\'t have to mean you lose the job. Here\'s how to understand what customers are really saying when they push back on price — and how to respond without folding.',
    metaTitle: 'How to Handle Price Objections Without Lowering Your Price | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['sales', 'pricing', 'objections', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=1200&auto=format&fit=crop&q=80',
    content: howToHandlePriceObjections,
  },
  {
    slug: 'how-ai-books-appointments-service-business',
    title: 'How AI Books Appointments for Service Businesses (Without a Human on the Phone)',
    description: 'Most service businesses lose jobs not because of bad work, but slow response. Here\'s exactly how AI appointment booking works, what it handles well, and what it takes to set up.',
    metaTitle: 'How AI Books Appointments for Service Businesses | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['AI', 'automation', 'appointment booking', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&auto=format&fit=crop&q=80',
    content: howAiBooksAppointmentsServiceBusiness,
  },
  {
    slug: 'what-you-need-to-build-an-ai-receptionist-service-business',
    title: 'What You Actually Need to Build an AI Receptionist for Your Service Business',
    description: 'An AI receptionist is not a single product — it\'s a stack of five specific components. Here\'s what each one does, what it costs, and how to decide whether to build it or hire it out.',
    metaTitle: 'What You Need to Build an AI Receptionist | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['AI', 'automation', 'receptionist', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200&auto=format&fit=crop&q=80',
    content: whatYouNeedToBuildAnAiReceptionistServiceBusiness,
  },
  {
    slug: 'do-you-need-a-crm-service-business',
    title: 'Do You Actually Need a CRM? An Honest Answer for Service Business Owners',
    description: 'Most service businesses either have no CRM or one they never use. Here\'s an honest breakdown of when a CRM actually helps, when it\'s overkill, and what to look for if you need one.',
    metaTitle: 'Do You Need a CRM? An Honest Answer for Service Businesses | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['CRM', 'automation', 'software', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80',
    content: doYouNeedACrmServiceBusiness,
  },
  {
    slug: 'how-to-reactivate-old-customers',
    title: 'How to Reactivate Old Customers (And Why It\'s Easier Than Getting New Ones)',
    description: 'Past customers already trust you. Here\'s a simple system to bring them back — who to target, what to send, when to send it, and how to automate the whole thing.',
    metaTitle: 'How to Reactivate Old Customers | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['customer reactivation', 'marketing', 'automation', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&auto=format&fit=crop&q=80',
    content: howToReactivateOldCustomers,
  },
  {
    slug: 'fence-installation-business-book-more-jobs',
    title: 'How Fence Companies Stop Losing Installs to the Competitor Who Calls Back First',
    description: 'Fence installation jobs are high-ticket and highly competitive. Here\'s how the busiest fence companies are capturing every lead — even when the crew is in the ground — and winning more installs without running more ads.',
    metaTitle: 'How Fence Companies Stop Losing Installs to the Competitor Who Calls Back First | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-17',
    tags: ['fence installation', 'AI automation', 'lead response', 'missed calls'],
    featuredImage: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=1200&auto=format&fit=crop&q=80',
    content: fenceInstallationBusinessBookMoreJobs,
  },
  {
    slug: 'what-your-website-needs-before-you-run-ads',
    title: 'What Your Website Needs Before You Run Ads (A Checklist for Service Businesses)',
    description: 'Running ads into a broken website is like turning on a faucet over a broken bucket. Here\'s the complete checklist of what needs to be in place before you spend a dollar on paid traffic.',
    metaTitle: 'What Your Website Needs Before You Run Ads | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['website', 'ads', 'conversion', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f5f989?w=1200&auto=format&fit=crop&q=80',
    content: whatYourWebsiteNeedsBeforeYouRunAds,
  },
  {
    slug: 'gutter-cleaning-business-book-more-jobs',
    title: 'Why Gutter Cleaning Companies Lose Their Best Leads During the Fall and Spring Rush',
    description: 'Gutter cleaning is seasonal, competitive, and booked on impulse. Here\'s how the busiest gutter companies capture every lead during peak season — even when the crew is on a roof and can\'t pick up.',
    metaTitle: 'Why Gutter Cleaning Companies Lose Their Best Leads During the Fall and Spring Rush | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-17',
    tags: ['gutter cleaning', 'AI automation', 'seasonal', 'missed calls'],
    featuredImage: 'https://images.unsplash.com/photo-1508873699-8b57b2d4f6b7?w=1200&auto=format&fit=crop&q=80',
    content: gutterCleaningBusinessBookMoreJobs,
  },
  {
    slug: 'appliance-repair-shop-book-more-jobs',
    title: 'Why Appliance Repair Shops Lose Jobs Before the Phone Stops Ringing',
    description: 'When a refrigerator dies or a washer quits mid-cycle, homeowners call two or three shops and book whoever answers first. Here\'s how independent appliance repair businesses are capturing every urgent call — and filling their schedules without hiring more staff.',
    metaTitle: 'Why Appliance Repair Shops Lose Jobs Before the Phone Stops Ringing | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-17',
    tags: ['appliance repair', 'AI automation', 'missed calls', 'lead response'],
    featuredImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&auto=format&fit=crop&q=80',
    content: applianceRepairShopBookMoreJobs,
  },
  {
    slug: 'how-to-turn-one-time-customers-into-recurring-revenue',
    title: 'How to Turn One-Time Service Calls Into Predictable, Recurring Revenue',
    description: 'Most service businesses trade time for money — one job, one payment, done. Here\'s how to build simple follow-up systems that bring customers back automatically and turn a job-by-job business into one with predictable monthly income.',
    metaTitle: 'How to Turn One-Time Customers Into Recurring Revenue | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-17',
    tags: ['recurring revenue', 'customer retention', 'automation', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&auto=format&fit=crop&q=80',
    content: howToTurnOneTimeCustomersIntoRecurringRevenue,
  },
  {
    slug: 'what-to-say-when-customer-says-ill-think-about-it',
    title: 'What to Say When a Customer Says "I\'ll Think About It" (Without Being Pushy)',
    description: '"I\'ll think about it" is the most common reason service business owners lose jobs they should have won. Here\'s what it actually means, what to say in the moment, and how to follow up without feeling like a salesperson.',
    metaTitle: 'What to Say When a Customer Says "I\'ll Think About It" | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-17',
    tags: ['sales', 'objections', 'service business', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=1200&auto=format&fit=crop&q=80',
    content: whatToSayWhenCustomerSaysIllThinkAboutIt,
  },
];
