import plumberChatWidget from './the-tool-plumbers-use-to-book-jobs-while-they-sleep.html?raw';
import whyPlumbersLoseJobsMidCall from './why-plumbers-lose-jobs-mid-call.html?raw';
import plumbingEstimateFollowUpAutomation from './plumbing-estimate-follow-up-automation.html?raw';
import hvacToolToBookMoreServiceCalls from './hvac-tool-to-book-more-service-calls.html?raw';
import hvacWinterEmergencyCallsAutomatedResponse from './hvac-winter-emergency-calls-automated-response.html?raw';
import rooferToolToCaptureStormLeads from './roofer-tool-to-capture-storm-leads.html?raw';
import howRoofingCompaniesStayBusyBetweenStorms from './how-roofing-companies-stay-busy-between-storms.html?raw';
import roofingReferralsGoogleReviewsAutomatedFollowUp from './roofing-referrals-google-reviews-automated-follow-up.html?raw';
import electricianToolToBookMoreJobs from './electrician-tool-to-book-more-jobs.html?raw';
import howElectriciansWinPanelUpgradeEvChargerJobs from './how-electricians-win-panel-upgrade-ev-charger-jobs.html?raw';
import electricianRepeatCustomersAutomatedFollowUp from './electrician-repeat-customers-automated-follow-up.html?raw';
import restaurantQrCodeLoyaltySystem from './restaurant-qr-code-loyalty-system.html?raw';
import pestControlToolToBookMoreJobs from './pest-control-tool-to-book-more-jobs.html?raw';
import lawnCareToolToBookMoreCustomers from './lawn-care-tool-to-book-more-customers.html?raw';
import garageDoorRepairToolToBookMoreJobs from './garage-door-repair-tool-to-book-more-jobs.html?raw';
import howMuchMissedCallsCostServiceBusiness from './how-much-missed-calls-cost-service-business.html?raw';
import leadResponseTimeWhySpeedWinsTheJob from './lead-response-time-why-speed-wins-the-job.html?raw';
import autoRepairShopToolToBookMoreJobs from './auto-repair-shop-tool-to-book-more-jobs.html?raw';
import howToGetMoreGoogleReviewsServiceBusiness from './how-to-get-more-google-reviews-service-business.html?raw';
import whatToTextCustomerAfterJobToGet5StarReview from './what-to-text-customer-after-job-to-get-5-star-review.html?raw';
import whyCustomersDontLeaveVoicemailsAnymore from './why-customers-dont-leave-voicemails-anymore.html?raw';
import completeGuideAiAutomationLocalServiceBusinesses from './complete-guide-ai-automation-local-service-businesses.html?raw';
import locksmithAiToolToBookMoreJobs from './locksmith-ai-tool-to-book-more-jobs.html?raw';
import cleaningServiceAiToolToBookMoreClients from './cleaning-service-ai-tool-to-book-more-clients.html?raw';
import aiVsHiringReceptionistServiceBusiness from './ai-vs-hiring-receptionist-service-business.html?raw';
import googleBusinessProfileMoreImportantThanWebsite from './google-business-profile-more-important-than-website.html?raw';
import pressureWashingAiToolToBookMoreJobs from './pressure-washing-ai-tool-to-book-more-jobs.html?raw';
import howToRespondToNegativeGoogleReviewsServiceBusiness from './how-to-respond-to-negative-google-reviews-service-business.html?raw';
import howServiceBusinessesStayBusyInSlowSeason from './how-service-businesses-stay-busy-in-slow-season.html?raw';
import howMuchShouldServiceBusinessSpendOnMarketing from './how-much-should-service-business-spend-on-marketing.html?raw';
import whyServiceBusinessLeadsGoCold from './why-service-business-leads-go-cold.html?raw';
import treeServiceBusinessStopLosingLeads from './tree-service-business-stop-losing-leads.html?raw';
import aboutPageThatConvertsServiceBusiness from './about-page-that-converts-service-business.html?raw';
import howToGetMoreReferralsServiceBusiness from './how-to-get-more-referrals-service-business.html?raw';
import poolServiceAiToolToBookMoreJobs from './pool-service-ai-tool-to-book-more-jobs.html?raw';
import handymanAiToolToBookMoreJobs from './handyman-ai-tool-to-book-more-jobs.html?raw';
import paintingContractorAiToolToBookMoreJobs from './painting-contractor-ai-tool-to-book-more-jobs.html?raw';
import howToPriceHomeServiceBusiness from './how-to-price-home-service-business.html?raw';
import whatIsCrmServiceBusiness from './what-is-crm-service-business.html?raw';
import windowCleaningAiToolToBookMoreJobs from './window-cleaning-ai-tool-to-book-more-jobs.html?raw';
import flooringContractorAiToolToBookMoreJobs from './flooring-contractor-ai-tool-to-book-more-jobs.html?raw';
import hvacTuneUpSeasonLeads from './hvac-tune-up-season-leads.html?raw';
import howToGetRepeatCustomersServiceBusiness from './how-to-get-repeat-customers-service-business.html?raw';
import howToDifferentiateYourServiceBusiness from './how-to-differentiate-your-service-business.html?raw';
import howToSetUpMissedCallTextBack from './how-to-set-up-missed-call-text-back.html?raw';
import howToAutomateGoogleReviewRequests from './how-to-automate-google-review-requests.html?raw';
import howToBuildLeadFollowUpSequence from './how-to-build-lead-follow-up-sequence.html?raw';
import howToAddOnlineBookingServiceBusiness from './how-to-add-online-booking-service-business.html?raw';
import howToSetUpAppointmentReminders from './how-to-set-up-appointment-reminders.html?raw';
import howToFollowUpAfterEstimate from './how-to-follow-up-after-estimate.html?raw';
import howToBuildReferralProgramServiceBusiness from './how-to-build-referral-program-service-business.html?raw';
import howToWriteServiceGuarantee from './how-to-write-service-guarantee.html?raw';
import howToTrackLeadsServiceBusiness from './how-to-track-leads-service-business.html?raw';
import howToHandlePriceObjections from './how-to-handle-price-objections.html?raw';
import howAiBooksAppointmentsServiceBusiness from './how-ai-books-appointments-service-business.html?raw';
import whatYouNeedToBuildAnAiReceptionistServiceBusiness from './what-you-need-to-build-an-ai-receptionist-service-business.html?raw';
import doYouNeedACrmServiceBusiness from './do-you-need-a-crm-service-business.html?raw';
import howToReactivateOldCustomers from './how-to-reactivate-old-customers.html?raw';
import whatYourWebsiteNeedsBeforeYouRunAds from './what-your-website-needs-before-you-run-ads.html?raw';
import fenceInstallationBusinessBookMoreJobs from './fence-installation-business-book-more-jobs.html?raw';
import gutterCleaningBusinessBookMoreJobs from './gutter-cleaning-business-book-more-jobs.html?raw';
import applianceRepairShopBookMoreJobs from './appliance-repair-shop-book-more-jobs.html?raw';
import howToTurnOneTimeCustomersIntoRecurringRevenue from './how-to-turn-one-time-customers-into-recurring-revenue.html?raw';
import whatToSayWhenCustomerSaysIllThinkAboutIt from './what-to-say-when-customer-says-ill-think-about-it.html?raw';
import howToReactivateLapsedChiropracticPatients from './how-to-reactivate-lapsed-chiropractic-patients.html?raw';
import howChiropractorsStopMissingNewPatientCalls from './how-chiropractors-stop-missing-new-patient-calls.html?raw';
import howToReactivateLapsedDentalPatients from './how-to-reactivate-lapsed-dental-patients.html?raw';
import dentalAppointmentRemindersReduceNoShows from './dental-appointment-reminders-reduce-no-shows.html?raw';
import howToReactivateLapsedMedSpaClients from './how-to-reactivate-lapsed-med-spa-clients.html?raw';
import medSpaConsultationFollowUpSequence from './med-spa-consultation-follow-up-sequence.html?raw';
import howToReactivateLapsedPhysicalTherapyPatients from './how-to-reactivate-lapsed-physical-therapy-patients.html?raw';
import howPhysicalTherapyPracticesImprovePatientAdherence from './how-physical-therapy-practices-improve-patient-adherence.html?raw';
import howChiropractorsGetMoreGoogleReviews from './how-chiropractors-get-more-google-reviews.html?raw';
import howDentalPracticesCaptureMoreNewPatientLeads from './how-dental-practices-capture-more-new-patient-leads.html?raw';
import howMedSpasGetMoreGoogleReviews from './how-med-spas-get-more-google-reviews.html?raw';
import howPhysicalTherapyPracticesCaptureNewPatientCalls from './how-physical-therapy-practices-capture-new-patient-calls.html?raw';
import howDentalPracticesFillHygieneScheduleGaps from './how-dental-practices-fill-hygiene-schedule-gaps.html?raw';
import howMedSpasCaptureAfterHoursLeads from './how-med-spas-capture-after-hours-leads.html?raw';
import howChiropracticPracticesReduceCancellations from './how-chiropractic-practices-reduce-cancellations.html?raw';
import howPhysicalTherapyPracticesIncreasePhysicianReferrals from './how-physical-therapy-practices-increase-physician-referrals.html?raw';
import garageDoorCompanyStopLosingAfterHoursCalls from './garage-door-company-stop-losing-after-hours-calls.html?raw';
import garageDoorCompanyRepeatCustomersMaintenance from './garage-door-company-repeat-customers-maintenance.html?raw';
import autoRepairShopStopMissingCalls from './auto-repair-shop-stop-missing-calls.html?raw';
import autoRepairServiceReminderSystemRepeatCustomers from './auto-repair-service-reminder-system-repeat-customers.html?raw';
import lawnCareWinSpringRushFastResponse from './lawn-care-win-spring-rush-fast-response.html?raw';
import lawnCareRecurringRevenueRetention from './lawn-care-recurring-revenue-retention.html?raw';
import pestControlFirstToAnswerWins from './pest-control-first-to-answer-wins.html?raw';
import pestControlRecurringPlansPredictableRevenue from './pest-control-recurring-plans-predictable-revenue.html?raw';

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  author: string;
  date: string;
  tags: string[];
  featuredImage?: string;
  metaTitle?: string;
  content: string;
}

export const posts: BlogPost[] = [
  {
    slug: 'garage-door-company-stop-losing-after-hours-calls',
    title: "How Garage Door Companies Can Stop Losing After-Hours Repair Calls",
    description: "Broken-spring calls cluster at night and on weekends. Here's how garage door companies answer every after-hours call — or text back instantly — and win the job.",
    metaTitle: "Stop Losing After-Hours Garage Door Calls | Wayne AI",
    author: "Wayne AI",
    date: '2026-07-05',
    tags: ["garage door", "missed calls", "automation"],
    featuredImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80',
    content: garageDoorCompanyStopLosingAfterHoursCalls,
  },
  {
    slug: 'garage-door-company-repeat-customers-maintenance',
    title: "How Garage Door Companies Turn One Repair Into Years of Business",
    description: "Garage doors get replaced once a decade — unless you give customers a reason to return. Tune-up reminders, review requests, and referral asks that run themselves.",
    metaTitle: "Turn One Garage Door Repair Into Years of Work | Wayne AI",
    author: "Wayne AI",
    date: '2026-07-05',
    tags: ["garage door", "customer retention", "automation"],
    featuredImage: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1200&auto=format&fit=crop&q=80',
    content: garageDoorCompanyRepeatCustomersMaintenance,
  },
  {
    slug: 'auto-repair-shop-stop-missing-calls',
    title: "How Auto Repair Shops Can Stop Missing Calls While They're Under the Hood",
    description: "Full bays mean missed calls — and missed calls mean customers booking elsewhere. How busy auto repair shops answer every call without hiring front-desk staff.",
    metaTitle: "Stop Missing Calls at Your Auto Repair Shop | Wayne AI",
    author: "Wayne AI",
    date: '2026-07-05',
    tags: ["auto repair", "missed calls", "automation"],
    featuredImage: 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=1200&auto=format&fit=crop&q=80',
    content: autoRepairShopStopMissingCalls,
  },
  {
    slug: 'auto-repair-service-reminder-system-repeat-customers',
    title: "The Service Reminder System That Keeps Auto Repair Bays Full Year-Round",
    description: "Every car you've fixed is future work. How auto repair shops use service reminders, win-back messages, and review requests to keep bays full year-round.",
    metaTitle: "Auto Repair Service Reminders That Fill Bays | Wayne AI",
    author: "Wayne AI",
    date: '2026-07-05',
    tags: ["auto repair", "customer retention", "automation"],
    featuredImage: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=1200&auto=format&fit=crop&q=80',
    content: autoRepairServiceReminderSystemRepeatCustomers,
  },
  {
    slug: 'lawn-care-win-spring-rush-fast-response',
    title: "How Lawn Care Businesses Win the Spring Rush Before Competitors Call Back",
    description: "In spring, the first lawn company to respond usually wins the yard. Here's how to answer every quote request instantly — even from the mower seat.",
    metaTitle: "Win the Spring Rush: Lawn Care Speed-to-Lead | Wayne AI",
    author: "Wayne AI",
    date: '2026-07-05',
    tags: ["lawn care", "lead generation", "automation"],
    featuredImage: 'https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=1200&auto=format&fit=crop&q=80',
    content: lawnCareWinSpringRushFastResponse,
  },
  {
    slug: 'lawn-care-recurring-revenue-retention',
    title: "Turning One-Time Mows Into Recurring Lawn Care Revenue",
    description: "One-time mows keep you on a treadmill. Learn how to turn first cuts into season contracts, timed upsells, and reviews that fill the whole street.",
    metaTitle: "Turn One-Time Mows Into Recurring Revenue | Wayne AI",
    author: "Wayne AI",
    date: '2026-07-05',
    tags: ["lawn care", "customer retention", "recurring revenue"],
    featuredImage: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=1200&auto=format&fit=crop&q=80',
    content: lawnCareRecurringRevenueRetention,
  },
  {
    slug: 'pest-control-first-to-answer-wins',
    title: "Why the First Pest Control Company to Answer Usually Wins the Job",
    description: "Pest emergencies go to the first company that responds. How missed-call text-back and after-hours capture stop panicked callers from dialing your competitor.",
    metaTitle: "First Pest Control Company to Answer Wins | Wayne AI",
    author: "Wayne AI",
    date: '2026-07-05',
    tags: ["pest control", "missed calls", "lead response"],
    featuredImage: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&auto=format&fit=crop&q=80',
    content: pestControlFirstToAnswerWins,
  },
  {
    slug: 'pest-control-recurring-plans-predictable-revenue',
    title: "How Pest Control Companies Build Predictable Revenue With Recurring Plans",
    description: "One-off jobs mean feast-or-famine. How to convert first treatments into quarterly plans, automate re-service reminders, and win back lapsed pest control accounts.",
    metaTitle: "Recurring Revenue Plans for Pest Control | Wayne AI",
    author: "Wayne AI",
    date: '2026-07-05',
    tags: ["pest control", "recurring revenue", "customer retention"],
    featuredImage: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=1200&auto=format&fit=crop&q=80',
    content: pestControlRecurringPlansPredictableRevenue,
  },
  {
    slug: 'the-tool-plumbers-use-to-book-jobs-while-they-sleep',
    title: 'How Plumbers Book Jobs While They Sleep With 24/7 Web Chat',
    description: 'Discover the AI webchat tool top plumbers are adding to their websites to capture leads 24/7 and book jobs automatically — even at 2am.',
    metaTitle: 'How Plumbers Book Jobs While They Sleep | Wayne AI',
    author: 'Wayne AI',
    date: '2025-03-15',
    tags: ['plumbing', 'lead generation', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=1200&auto=format&fit=crop&q=80',
    content: plumberChatWidget,
  },
  {
    slug: 'why-plumbers-lose-jobs-mid-call',
    title: 'Why Plumbers Lose Jobs While They\'re on a Job (And the Fix That Runs Itself)',
    description: 'Most plumbers miss 5+ calls a week mid-repair without realizing it. Here\'s what those missed calls cost you — and how a simple text-back wins them back.',
    metaTitle: 'Why Plumbers Lose Jobs Mid-Call | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['plumbing', 'missed calls', 'lead response', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&auto=format&fit=crop&q=80',
    content: whyPlumbersLoseJobsMidCall,
  },
  {
    slug: 'plumbing-estimate-follow-up-automation',
    title: 'Why Your Plumbing Estimates Go Cold — And How Automated Follow-Up Fixes It',
    description: 'Plumbing revenue doesn\'t walk out the front door — it leaks through estimates that never got a second follow-up. Here\'s how an automated sequence closes more.',
    metaTitle: 'Why Plumbing Estimates Go Cold | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['plumbing', 'estimate follow-up', 'lead nurture', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&auto=format&fit=crop&q=80',
    content: plumbingEstimateFollowUpAutomation,
  },
  {
    slug: 'hvac-tool-to-book-more-service-calls',
    title: 'How HVAC Companies Book More Service Calls Without Answering Every Phone',
    description: 'How smart HVAC companies use AI to respond to leads instantly, book service calls automatically, and stop losing jobs to competitors who pick up faster.',
    metaTitle: 'How HVAC Companies Book More Service Calls | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-03',
    tags: ["HVAC","lead generation","automation"],
    featuredImage: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1200&auto=format&fit=crop&q=80',
    content: hvacToolToBookMoreServiceCalls,
  },
  {
    slug: 'roofer-tool-to-capture-storm-leads',
    title: 'How Roofers Capture Storm Leads Before the Competition Gets There',
    description: 'After a storm, every roofer chases the same leads. Here\'s how smart roofing companies respond first, book inspections automatically, and close more jobs.',
    metaTitle: "The Tool Roofers Use to Capture Storm Leads First | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["roofing","lead generation","automation"],
    featuredImage: 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=1200&auto=format&fit=crop&q=80',
    content: rooferToolToCaptureStormLeads,
  },
  {
    slug: 'how-roofing-companies-stay-busy-between-storms',
    title: "How Roofing Companies Stay Busy Between Storms (Without Waiting for the Next One)",
    description: 'Storm season fills the calendar fast — the other 48 weeks don\'t have to be a grind. Here\'s how busy roofers generate work year-round with reactivation and follow-up.',
    metaTitle: "How Roofing Companies Stay Busy Between Storms | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-18',
    tags: ["roofing", "slow season", "lead generation", "automation"],
    featuredImage: 'https://images.unsplash.com/photo-1632823471565-1ecdf5c6da2e?w=1200&auto=format&fit=crop&q=80',
    content: howRoofingCompaniesStayBusyBetweenStorms,
  },
  {
    slug: 'roofing-referrals-google-reviews-automated-follow-up',
    title: 'How Roofing Companies Build a Self-Sustaining Lead Engine With Referrals and Reviews',
    description: 'Most roofers wait for the next storm. The ones with full pipelines built a referral and review engine that runs on autopilot after every job closes.',
    metaTitle: 'Roofing Referrals & Reviews on Autopilot | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['roofing', 'referrals', 'google reviews', 'automation', 'follow-up'],
    featuredImage: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&auto=format&fit=crop&q=80',
    content: roofingReferralsGoogleReviewsAutomatedFollowUp,
  },
  {
    slug: 'electrician-tool-to-book-more-jobs',
    title: 'How Busy Electricians Book More Jobs Without Playing Phone Tag All Day',
    description: 'Every missed call is a job that went to another electrician. Here\'s how busy electrical contractors respond instantly and book more service calls automatically.',
    metaTitle: "The Tool Electricians Use to Book More Jobs | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["electrician","lead generation","automation"],
    featuredImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&auto=format&fit=crop&q=80',
    content: electricianToolToBookMoreJobs,
  },
  {
    slug: 'how-electricians-win-panel-upgrade-ev-charger-jobs',
    title: "How Electricians Are Winning More Panel Upgrades and EV Charger Jobs",
    description: 'Panel upgrades and EV charger installs are high-ticket jobs most contractors lose before the first conversation. Here\'s how fast lead response wins them.',
    metaTitle: 'Win More Panel Upgrade & EV Charger Jobs | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-18',
    tags: ["electrician","lead generation","EV charger","panel upgrade"],
    featuredImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&auto=format&fit=crop&q=80',
    content: howElectriciansWinPanelUpgradeEvChargerJobs,
  },
  {
    slug: 'electrician-repeat-customers-automated-follow-up',
    title: 'Why Electricians Lose Repeat Business (And How Automated Follow-Up Fixes It)',
    description: 'Most electricians finish a job and never call that customer again. Here\'s how automated follow-up keeps you top of mind and turns past customers into new bookings.',
    metaTitle: 'How Electricians Get More Repeat Business | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['electrician', 'repeat customers', 'follow-up', 'automation', 'referrals'],
    featuredImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&auto=format&fit=crop&q=80',
    content: electricianRepeatCustomersAutomatedFollowUp,
  },
  {
    slug: 'restaurant-qr-code-loyalty-system',
    title: "The QR Code Trick Restaurants Are Using to Turn One-Time Diners Into Regulars",
    description: 'A QR code on the table and a free-dessert offer give your restaurant a direct line to every diner. Here\'s how to turn one-time customers into loyal regulars.',
    metaTitle: 'How Restaurants Build Loyal Regulars | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["restaurant","loyalty","automation"],
    featuredImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&auto=format&fit=crop&q=80',
    content: restaurantQrCodeLoyaltySystem,
  },
  {
    slug: 'pest-control-tool-to-book-more-jobs',
    title: 'How Pest Control Companies Book More Jobs by Responding First',
    description: 'When bugs show up, homeowners call every pest control company and go with whoever answers first. Here\'s how to respond instantly and book more recurring plans.',
    featuredImage: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&auto=format&fit=crop&q=80',
    metaTitle: 'How Pest Control Companies Book More Jobs | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["pest control","lead generation","automation"],
    content: pestControlToolToBookMoreJobs,
  },
  {
    slug: 'lawn-care-tool-to-book-more-customers',
    title: 'How Lawn Care Companies Book More Customers Without Losing the Spring Rush',
    description: 'Every spring, 50 homeowners call in one week and the companies that respond first fill their routes. Here\'s how to capture every lead and lock in loyal customers.',
    featuredImage: 'https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=1200&auto=format&fit=crop&q=80',
    metaTitle: 'How Lawn Care Companies Win the Spring Rush | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["lawn care","lead generation","automation"],
    content: lawnCareToolToBookMoreCustomers,
  },
  {
    slug: 'garage-door-repair-tool-to-book-more-jobs',
    title: 'How Garage Door Companies Book More Jobs Without Missing a Single Urgent Call',
    description: 'Broken springs don\'t wait for business hours. See how garage door companies capture every urgent call — even at 6am — and book more high-ticket jobs automatically.',
    featuredImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80',
    metaTitle: 'How Garage Door Pros Capture Every Call | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["garage door","lead generation","automation"],
    content: garageDoorRepairToolToBookMoreJobs,
  },
  {
    slug: 'how-much-missed-calls-cost-service-business',
    title: "How Much Are Missed Calls Actually Costing Your Service Business?",
    description: "Most service business owners think missed calls are a minor inconvenience. The math says otherwise. Here's what unanswered phones are really costing you.",
    featuredImage: 'https://images.unsplash.com/photo-1534536281715-e28d76689b4d?w=1200&auto=format&fit=crop&q=80',
    metaTitle: "How Much Do Missed Calls Cost a Service Business? | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["lead generation","missed calls","revenue"],
    content: howMuchMissedCallsCostServiceBusiness,
  },
  {
    slug: 'lead-response-time-why-speed-wins-the-job',
    title: "The 5-Minute Lead Response Rule: Why Speed Wins or Loses the Job",
    description: 'Leads contacted within 5 minutes are far more likely to convert. Here\'s why response speed is the biggest factor in winning or losing local service jobs.',
    featuredImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&auto=format&fit=crop&q=80',
    metaTitle: 'The 5-Minute Lead Response Rule | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["lead generation","response time","automation"],
    content: leadResponseTimeWhySpeedWinsTheJob,
  },
  {
    slug: 'auto-repair-shop-tool-to-book-more-jobs',
    title: "Why Auto Repair Shops Lose Jobs Every Time They Miss a Call",
    description: 'Independent auto repair shops lose real revenue every time a call goes unanswered. Here\'s how AI-powered instant text response fills your bays without new staff.',
    featuredImage: 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=1200&auto=format&fit=crop&q=80',
    metaTitle: "Auto Repair Shop Tool to Book More Jobs | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["auto repair","lead generation","automation"],
    content: autoRepairShopToolToBookMoreJobs,
  },
  {
    slug: 'how-to-get-more-google-reviews-service-business',
    title: "How to Get More Google Reviews for Your Service Business (Without Begging)",
    description: 'Most satisfied customers never leave a review — they just move on. Here\'s the exact system service businesses use to collect more Google reviews automatically.',
    featuredImage: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&auto=format&fit=crop&q=80',
    metaTitle: 'How to Get More Google Reviews | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["google reviews","reputation","local SEO"],
    content: howToGetMoreGoogleReviewsServiceBusiness,
  },
  {
    slug: 'what-to-text-customer-after-job-to-get-5-star-review',
    title: "What to Text a Customer After a Job to Get a 5-Star Review",
    description: 'Most businesses leave reviews on the table because no one follows up. Here are 3 real text templates you can send today — plus how to automate the whole thing.',
    featuredImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&auto=format&fit=crop&q=80',
    metaTitle: 'What to Text a Customer for a 5-Star Review | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["google reviews","reputation","customer follow-up"],
    content: whatToTextCustomerAfterJobToGet5StarReview,
  },
  {
    slug: 'why-customers-dont-leave-voicemails-anymore',
    title: "Why Customers Don't Leave Voicemails Anymore (And What That's Costing You)",
    description: 'If you\'re counting on voicemail to catch missed leads, you\'re losing jobs daily. Here\'s how customer behavior has changed — and what actually works now.',
    featuredImage: 'https://images.unsplash.com/photo-1534536281715-e28d76689b4d?w=1200&auto=format&fit=crop&q=80',
    metaTitle: "Why Customers Don't Leave Voicemails Anymore | Wayne AI",
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["lead generation","missed calls","customer behavior"],
    content: whyCustomersDontLeaveVoicemailsAnymore,
  },
  {
    slug: 'complete-guide-ai-automation-local-service-businesses',
    title: "The Complete Guide to AI Automation for Local Service Businesses",
    description: 'A complete guide to AI automation for local service businesses: missed-call recovery, instant lead response, appointment reminders, and review generation.',
    featuredImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80',
    metaTitle: 'AI Automation for Local Service Businesses | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["AI automation","local service business","lead generation","guide"],
    content: completeGuideAiAutomationLocalServiceBusinesses,
  },
  {
    slug: 'locksmith-ai-tool-to-book-more-jobs',
    title: 'How Locksmiths Book More Emergency Jobs Without Answering Every Call',
    description: 'Locksmiths lose emergency jobs every day to a single missed call. Here\'s how automated text-back and lead response capture after-hours revenue without new staff.',
    metaTitle: 'How Locksmiths Book More Emergency Jobs | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["locksmith", "AI automation", "missed calls", "lead response"],
    featuredImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&auto=format&fit=crop&q=80",
    content: locksmithAiToolToBookMoreJobs,
  },
  {
    slug: 'cleaning-service-ai-tool-to-book-more-clients',
    title: "How Cleaning Services Are Filling Their Schedules Faster With AI Lead Response",
    description: 'If your cleaning business isn\'t answering leads within minutes, you\'re losing recurring clients worth thousands a year. Here\'s how AI lead response changes that.',
    metaTitle: 'How Cleaning Services Fill Their Schedules | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["cleaning service", "AI automation", "lead response", "recurring revenue"],
    featuredImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&auto=format&fit=crop&q=80",
    content: cleaningServiceAiToolToBookMoreClients,
  },
  {
    slug: 'ai-vs-hiring-receptionist-service-business',
    title: "AI vs. Hiring a Receptionist: What Actually Makes Sense for a Service Business",
    description: 'Thinking about hiring a receptionist? Run the real numbers first — and see where AI automation beats a full-time hire, and where it doesn\'t.',
    metaTitle: 'AI vs. Hiring a Receptionist | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["AI automation", "receptionist", "service business", "cost comparison"],
    featuredImage: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&auto=format&fit=crop&q=80",
    content: aiVsHiringReceptionistServiceBusiness,
  },
  {
    slug: 'google-business-profile-more-important-than-website',
    title: "Why Your Google Business Profile Matters More Than Your Website",
    description: 'Most owners pour money into websites while ignoring the one thing that actually drives calls — their Google Business Profile. Here\'s why GBP matters more.',
    metaTitle: 'Google Business Profile vs. Your Website | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["Google Business Profile", "local SEO", "service business", "Google Maps"],
    featuredImage: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=1200&auto=format&fit=crop&q=80",
    content: googleBusinessProfileMoreImportantThanWebsite,
  },
  {
    slug: 'pressure-washing-ai-tool-to-book-more-jobs',
    title: "How Pressure Washing Companies Are Booking More Jobs Without Playing Phone Tag",
    description: 'Spring is make-or-break for pressure washing. Here\'s how missed-call text-back helps owner-operators capture more jobs without stopping to answer the phone.',
    metaTitle: 'How Pressure Washing Companies Book More Jobs | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["pressure washing", "AI automation", "missed calls", "seasonal"],
    featuredImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80",
    content: pressureWashingAiToolToBookMoreJobs,
  },
  {
    slug: 'how-to-respond-to-negative-google-reviews-service-business',
    title: "How to Respond to Negative Google Reviews (Without Making It Worse)",
    description: 'A 1-star review just landed on your profile. Here\'s exactly how service businesses should respond — with templates, rules, and a long-game reputation strategy.',
    metaTitle: 'How to Respond to Negative Google Reviews | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["Google reviews", "reputation management", "service business", "customer service"],
    featuredImage: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&auto=format&fit=crop&q=80",
    content: howToRespondToNegativeGoogleReviewsServiceBusiness,
  },
  {
    slug: 'how-service-businesses-stay-busy-in-slow-season',
    title: "How to Keep Your Service Business Busy When the Slow Season Hits",
    description: 'The slow season is real, but the busiest businesses aren\'t just lucky — they built systems during the peak. Here are five tactics to fill the calendar back up.',
    metaTitle: 'Keep Your Service Business Busy in Slow Season | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["slow season", "service business", "marketing", "customer reactivation"],
    featuredImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&auto=format&fit=crop&q=80",
    content: howServiceBusinessesStayBusyInSlowSeason,
  },
  {
    slug: 'how-much-should-service-business-spend-on-marketing',
    title: "How Much Should a Local Service Business Spend on Marketing?",
    description: 'Real numbers and honest benchmarks for how local service businesses should allocate a marketing budget — from $1,500 to $5,000 a month.',
    metaTitle: 'How Much Should You Spend on Marketing? | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-02',
    tags: ["marketing budget", "service business", "local marketing", "ROI"],
    featuredImage: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&auto=format&fit=crop&q=80",
    content: howMuchShouldServiceBusinessSpendOnMarketing,
  },
  {
    slug: 'why-service-business-leads-go-cold',
    title: 'The 3-Day Window: Why Most Service Business Leads Go Cold and Never Come Back',
    description: 'Most service business leads die within 24 hours — not because the customer lost interest, but because no one followed up fast enough. Here\'s how to fix it.',
    metaTitle: 'Why Service Business Leads Go Cold | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-02',
    tags: ['lead follow-up', 'service business', 'lead response', 'conversion'],
    featuredImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&auto=format&fit=crop&q=80',
    content: whyServiceBusinessLeadsGoCold,
  },
  {
    slug: 'tree-service-business-stop-losing-leads',
    title: "Why Tree Service Companies Lose Jobs Before They Even Know Someone Called",
    description: 'Tree service companies lose high-value jobs every day — not for bad work, but because they can\'t answer the phone mid-job. Here\'s how automation fixes that.',
    metaTitle: 'Why Tree Service Companies Lose Jobs | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-03',
    tags: ["tree service", "AI automation", "missed calls", "lead response"],
    featuredImage: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=1200&auto=format&fit=crop&q=80",
    content: treeServiceBusinessStopLosingLeads,
  },
  {
    slug: 'about-page-that-converts-service-business',
    title: 'Your "About Us" Page Is Losing You Customers. Here\'s How to Fix It.',
    description: "Most service business About pages are generic placeholders that kill trust instead of building it. Here's what to put on yours — and what to cut.",
    metaTitle: 'How to Write an About Page That Converts | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-03',
    tags: ["website", "conversion", "service business", "about page"],
    featuredImage: "https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=1200&auto=format&fit=crop&q=80",
    content: aboutPageThatConvertsServiceBusiness,
  },
  {
    slug: 'how-to-get-more-referrals-service-business',
    title: "The Simplest Way to Get More Referrals From Customers Who Already Love You",
    description: 'Referrals are the best leads you\'ll ever get — but they don\'t happen on their own. Here\'s how to build a simple system that turns happy customers into referrals.',
    metaTitle: 'How to Get More Referrals | Wayne AI',
    author: "Wayne AI",
    date: '2026-04-03',
    tags: ["referrals", "service business", "customer retention", "word of mouth"],
    featuredImage: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&auto=format&fit=crop&q=80",
    content: howToGetMoreReferralsServiceBusiness,
  },
  {
    slug: 'pool-service-ai-tool-to-book-more-jobs',
    title: 'Why Pool Service Companies Lose Leads After Hours (And How to Fix It)',
    description: 'Pool service companies miss most of their leads after hours. Here\'s why it happens and how AI automation helps you capture and book those jobs automatically.',
    metaTitle: 'Why Pool Service Companies Lose After-Hours Leads',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['pool service', 'AI automation', 'lead response', 'after hours'],
    featuredImage: 'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=1200&auto=format&fit=crop&q=80',
    content: poolServiceAiToolToBookMoreJobs,
  },
  {
    slug: 'handyman-ai-tool-to-book-more-jobs',
    title: 'How Handyman Businesses Book More Jobs Without Answering Every Call',
    description: 'Missed calls cost handyman businesses real jobs. Learn how AI automation handles lead capture, follow-up, and booking so you never lose work to voicemail again.',
    metaTitle: 'How Handyman Businesses Book More Jobs Without Every Call',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['handyman', 'AI automation', 'missed calls', 'lead response'],
    featuredImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&auto=format&fit=crop&q=80',
    content: handymanAiToolToBookMoreJobs,
  },
  {
    slug: 'painting-contractor-ai-tool-to-book-more-jobs',
    title: 'How Painting Contractors Stop Losing Bids to Faster Competitors',
    description: 'Painting contractors lose jobs every week to faster-responding competitors. Learn how AI automation closes that gap and keeps your calendar full.',
    metaTitle: 'How Painting Contractors Stop Losing Bids to Faster Rivals',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['painting contractor', 'AI automation', 'lead response', 'estimate booking'],
    featuredImage: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=1200&auto=format&fit=crop&q=80',
    content: paintingContractorAiToolToBookMoreJobs,
  },
  {
    slug: 'how-to-price-home-service-business',
    title: 'How to Price Your Home Service Business (Without Losing Jobs or Leaving Money on the Table)',
    description: 'Stop guessing at your prices. Learn the exact framework to calculate costs, research your market, and charge what you\'re worth without losing jobs.',
    metaTitle: 'How to Price Your Home Service Business Right',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['pricing', 'service business', 'profit margin', 'business advice'],
    featuredImage: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&auto=format&fit=crop&q=80',
    content: howToPriceHomeServiceBusiness,
  },
  {
    slug: 'what-is-crm-service-business',
    title: 'What Is a CRM and Does Your Service Business Actually Need One?',
    description: 'CRM stands for Customer Relationship Manager — but what does that mean for a plumber or HVAC tech? Here\'s what it does, and whether your business needs one.',
    metaTitle: 'What Is a CRM? Do Service Businesses Actually Need One?',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['CRM', 'service business', 'lead management', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&auto=format&fit=crop&q=80',
    content: whatIsCrmServiceBusiness,
  },
  {
    slug: 'window-cleaning-ai-tool-to-book-more-jobs',
    title: 'How Window Cleaning Companies Fill Their Schedule Every Spring Without Missing a Call',
    description: 'Missing calls during spring rush costs window cleaning companies real jobs. Here\'s how automated follow-up fills your schedule without adding staff.',
    metaTitle: 'How Window Cleaners Book More Jobs This Spring',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['window cleaning', 'AI automation', 'missed calls', 'spring season'],
    featuredImage: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=1200&auto=format&fit=crop&q=80',
    content: windowCleaningAiToolToBookMoreJobs,
  },
  {
    slug: 'flooring-contractor-ai-tool-to-book-more-jobs',
    title: 'How Flooring Contractors Win More Estimates Before the Competition Calls Back',
    description: 'Flooring contractors lose jobs to faster competitors every day. Learn how automated follow-up helps you capture leads before anyone else calls back.',
    metaTitle: 'How Flooring Contractors Win More Estimates & Jobs',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['flooring contractor', 'AI automation', 'lead response', 'estimates'],
    featuredImage: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=1200&auto=format&fit=crop&q=80',
    content: flooringContractorAiToolToBookMoreJobs,
  },
  {
    slug: 'hvac-tune-up-season-leads',
    title: 'Why HVAC Companies Lose Tune-Up Season Leads (And the Fix That Runs Itself)',
    description: 'Spring tune-up season floods your phone lines. Learn why HVAC companies miss so many leads and how automated follow-up captures every one.',
    metaTitle: 'Why HVAC Companies Lose Tune-Up Season Leads',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['HVAC', 'seasonal', 'AI automation', 'missed calls', 'tune-up'],
    featuredImage: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1200&auto=format&fit=crop&q=80',
    content: hvacTuneUpSeasonLeads,
  },
  {
    slug: 'hvac-winter-emergency-calls-automated-response',
    title: 'No Heat at Midnight: How HVAC Companies Can Capture Winter Emergency Calls Without Being on Call 24/7',
    description: 'Winter no-heat emergencies are the highest-stakes HVAC lead — the first company to respond wins. Here\'s how automated intake triages and books them for you.',
    metaTitle: 'HVAC: Capture Winter Emergency Calls | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['HVAC', 'winter', 'emergency calls', 'automation', 'no-heat'],
    featuredImage: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1200&auto=format&fit=crop&q=80',
    content: hvacWinterEmergencyCallsAutomatedResponse,
  },
  {
    slug: 'how-to-get-repeat-customers-service-business',
    title: 'The Easiest Way to Get More Repeat Business From Customers You Already Have',
    description: 'Your best new customer is one you already have. Learn simple tactics and automation to win repeat business from customers who already trust you.',
    metaTitle: 'Get More Repeat Customers for Your Service Business',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['repeat customers', 'customer retention', 'service business', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&auto=format&fit=crop&q=80',
    content: howToGetRepeatCustomersServiceBusiness,
  },
  {
    slug: 'how-to-differentiate-your-service-business',
    title: 'How to Explain What Makes Your Business Different (Without Sounding Like Everyone Else)',
    description: 'Every competitor claims "licensed, insured, 5-star service." Learn how to find and communicate what actually makes your service business different.',
    metaTitle: 'How to Make Your Service Business Stand Out',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['marketing', 'differentiation', 'service business', 'positioning'],
    featuredImage: 'https://images.unsplash.com/photo-1664575602276-acd073f104c1?w=1200&auto=format&fit=crop&q=80',
    content: howToDifferentiateYourServiceBusiness,
  },
  {
    slug: 'how-to-set-up-missed-call-text-back',
    title: 'How to Set Up a Missed-Call Text-Back for Your Service Business (Step by Step)',
    description: 'A missed call doesn\'t have to mean a lost lead. Here\'s how to set up an automated text-back that responds in seconds — so you keep the conversation alive.',
    metaTitle: 'How to Set Up Missed-Call Text-Back | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['automation', 'lead generation', 'missed calls', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1534536281715-e28d76689b4d?w=1200&auto=format&fit=crop&q=80',
    content: howToSetUpMissedCallTextBack,
  },
  {
    slug: 'how-to-automate-google-review-requests',
    title: 'How to Automate Google Review Requests After Every Job (Without Asking Awkwardly in Person)',
    description: 'Stop relying on techs to remember. Here\'s how to build an automated review request that goes out at the right moment — every time, hands-free.',
    metaTitle: 'How to Automate Google Review Requests | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['reviews', 'automation', 'google', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&auto=format&fit=crop&q=80',
    content: howToAutomateGoogleReviewRequests,
  },
  {
    slug: 'how-to-build-lead-follow-up-sequence',
    title: 'How to Build a Lead Follow-Up Sequence That Books Jobs While You\'re on the Job',
    description: 'Most service leads go cold because nobody followed up. Here\'s how to build a 5-touch automated sequence that stays on leads for a week — hands-free.',
    metaTitle: 'How to Build a Lead Follow-Up Sequence | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['automation', 'lead generation', 'follow-up', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80',
    content: howToBuildLeadFollowUpSequence,
  },
  {
    slug: 'how-to-add-online-booking-service-business',
    title: 'How to Add Online Booking to Your Service Business Website (Without Hiring a Developer)',
    description: 'If customers can\'t book when they\'re ready, they\'ll find someone who lets them. Here\'s how to set up online booking for your service business, step by step.',
    metaTitle: 'How to Add Online Booking to Your Site | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['booking', 'automation', 'website', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&auto=format&fit=crop&q=80',
    content: howToAddOnlineBookingServiceBusiness,
  },
  {
    slug: 'how-to-set-up-appointment-reminders',
    title: 'How to Set Up Automated Appointment Reminders That Cut No-Shows (Step by Step)',
    description: 'No-shows cost time, money, and a slot you could have filled. Here\'s how to build automated reminders that confirm appointments and catch cancellations early.',
    metaTitle: 'How to Set Up Appointment Reminders | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['automation', 'appointments', 'no-shows', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&auto=format&fit=crop&q=80',
    content: howToSetUpAppointmentReminders,
  },
  {
    slug: 'how-to-follow-up-after-estimate',
    title: 'How to Write a Follow-Up After Giving an Estimate (With Templates)',
    description: 'Most estimates don\'t get rejected — they get forgotten. Here\'s how to follow up after a quote, what to say at each touch, and real templates you can copy.',
    metaTitle: 'How to Follow Up After Giving an Estimate | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['sales', 'estimates', 'follow-up', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&auto=format&fit=crop&q=80',
    content: howToFollowUpAfterEstimate,
  },
  {
    slug: 'how-to-build-referral-program-service-business',
    title: 'How to Build a Simple Referral Program for Your Service Business (Without Software)',
    description: 'Referrals are your best leads, but most businesses treat them as an accident. Here\'s how to build a referral program with a clear ask, an incentive, and follow-up.',
    metaTitle: 'How to Build a Referral Program | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['referrals', 'marketing', 'growth', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&auto=format&fit=crop&q=80',
    content: howToBuildReferralProgramServiceBusiness,
  },
  {
    slug: 'how-to-write-service-guarantee',
    title: 'How to Write a Service Guarantee That Wins Jobs (And What to Avoid)',
    description: '"Satisfaction guaranteed" means nothing. Here\'s how to write a specific, credible guarantee that builds trust with skeptical customers — and what to leave out.',
    metaTitle: 'How to Write a Service Guarantee That Wins Jobs | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['trust', 'marketing', 'conversion', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=1200&auto=format&fit=crop&q=80',
    content: howToWriteServiceGuarantee,
  },
  {
    slug: 'how-to-track-leads-service-business',
    title: 'How to Track Where Your Leads Are Coming From (Without a Marketing Degree)',
    description: 'Most owners spend on marketing with no idea which channel sends jobs. Here\'s a simple system to find out — no analytics degree required.',
    metaTitle: 'How to Track Where Your Leads Come From | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['marketing', 'lead tracking', 'analytics', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80',
    content: howToTrackLeadsServiceBusiness,
  },
  {
    slug: 'how-to-handle-price-objections',
    title: 'How to Handle a Price Objection Without Lowering Your Price',
    description: '"I got a cheaper quote" doesn\'t have to lose you the job. Here\'s what customers really mean when they push back on price — and how to respond without folding.',
    metaTitle: 'How to Handle Price Objections | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['sales', 'pricing', 'objections', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=1200&auto=format&fit=crop&q=80',
    content: howToHandlePriceObjections,
  },
  {
    slug: 'how-ai-books-appointments-service-business',
    title: 'How AI Books Appointments for Service Businesses (Without a Human on the Phone)',
    description: 'Most service businesses lose jobs to slow response, not bad work. Here\'s exactly how AI appointment booking works, what it handles well, and how to set it up.',
    metaTitle: 'How AI Books Appointments for Service Businesses | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['AI', 'automation', 'appointment booking', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&auto=format&fit=crop&q=80',
    content: howAiBooksAppointmentsServiceBusiness,
  },
  {
    slug: 'what-you-need-to-build-an-ai-receptionist-service-business',
    title: 'What You Actually Need to Build an AI Receptionist for Your Service Business',
    description: 'An AI receptionist isn\'t one product — it\'s a stack of five components. Here\'s what each does, what it costs, and whether to build it or hire it out.',
    metaTitle: 'What You Need to Build an AI Receptionist | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['AI', 'automation', 'receptionist', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200&auto=format&fit=crop&q=80',
    content: whatYouNeedToBuildAnAiReceptionistServiceBusiness,
  },
  {
    slug: 'do-you-need-a-crm-service-business',
    title: 'Do You Actually Need a CRM? An Honest Answer for Service Business Owners',
    description: 'Most service businesses have no CRM or one they never use. Here\'s an honest breakdown of when a CRM helps, when it\'s overkill, and what to look for.',
    metaTitle: 'Do You Need a CRM? An Honest Answer | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['CRM', 'automation', 'software', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80',
    content: doYouNeedACrmServiceBusiness,
  },
  {
    slug: 'how-to-reactivate-old-customers',
    title: 'How to Reactivate Old Customers (And Why It\'s Easier Than Getting New Ones)',
    description: 'Past customers already trust you. Here\'s a simple system to bring them back — who to target, what to send, when to send it, and how to automate the whole thing.',
    metaTitle: 'How to Reactivate Old Customers | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['customer reactivation', 'marketing', 'automation', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&auto=format&fit=crop&q=80',
    content: howToReactivateOldCustomers,
  },
  {
    slug: 'fence-installation-business-book-more-jobs',
    title: 'How Fence Companies Stop Losing Installs to the Competitor Who Calls Back First',
    description: 'Fence installs are high-ticket and competitive. Here\'s how the busiest fence companies capture every lead — even with the crew in the ground — and win more jobs.',
    metaTitle: 'How Fence Companies Stop Losing Installs | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-17',
    tags: ['fence installation', 'AI automation', 'lead response', 'missed calls'],
    featuredImage: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=1200&auto=format&fit=crop&q=80',
    content: fenceInstallationBusinessBookMoreJobs,
  },
  {
    slug: 'what-your-website-needs-before-you-run-ads',
    title: 'What Your Website Needs Before You Run Ads (A Checklist for Service Businesses)',
    description: 'Running ads to a broken website is like a faucet over a broken bucket. Here\'s the complete checklist of what to fix before you spend a dollar on paid traffic.',
    metaTitle: 'What Your Website Needs Before You Run Ads | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-03',
    tags: ['website', 'ads', 'conversion', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f5f989?w=1200&auto=format&fit=crop&q=80',
    content: whatYourWebsiteNeedsBeforeYouRunAds,
  },
  {
    slug: 'gutter-cleaning-business-book-more-jobs',
    title: 'Why Gutter Cleaning Companies Lose Their Best Leads During the Fall and Spring Rush',
    description: 'Gutter cleaning is seasonal, competitive, and booked on impulse. Here\'s how the busiest companies capture every lead during peak — even with the crew on a roof.',
    metaTitle: 'Why Gutter Companies Lose Their Best Leads | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-17',
    tags: ['gutter cleaning', 'AI automation', 'seasonal', 'missed calls'],
    featuredImage: 'https://images.unsplash.com/photo-1508873699-8b57b2d4f6b7?w=1200&auto=format&fit=crop&q=80',
    content: gutterCleaningBusinessBookMoreJobs,
  },
  {
    slug: 'appliance-repair-shop-book-more-jobs',
    title: 'Why Appliance Repair Shops Lose Jobs Before the Phone Stops Ringing',
    description: 'When an appliance dies, homeowners call two or three shops and book whoever answers first. Here\'s how repair businesses capture every urgent call without new staff.',
    metaTitle: 'Why Appliance Repair Shops Lose Jobs | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-17',
    tags: ['appliance repair', 'AI automation', 'missed calls', 'lead response'],
    featuredImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&auto=format&fit=crop&q=80',
    content: applianceRepairShopBookMoreJobs,
  },
  {
    slug: 'how-to-turn-one-time-customers-into-recurring-revenue',
    title: 'How to Turn One-Time Service Calls Into Predictable, Recurring Revenue',
    description: 'Most service businesses trade time for money — one job, one payment. Here\'s how simple follow-up systems bring customers back and build predictable income.',
    metaTitle: 'Turn One-Time Customers Into Recurring Revenue | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-17',
    tags: ['recurring revenue', 'customer retention', 'automation', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&auto=format&fit=crop&q=80',
    content: howToTurnOneTimeCustomersIntoRecurringRevenue,
  },
  {
    slug: 'what-to-say-when-customer-says-ill-think-about-it',
    title: 'What to Say When a Customer Says "I\'ll Think About It" (Without Being Pushy)',
    description: '"I\'ll think about it" is the most common reason owners lose jobs they should win. Here\'s what it really means, what to say, and how to follow up.',
    metaTitle: 'What to Say to "I\'ll Think About It" | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-17',
    tags: ['sales', 'objections', 'service business', 'how-to'],
    featuredImage: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=1200&auto=format&fit=crop&q=80',
    content: whatToSayWhenCustomerSaysIllThinkAboutIt,
  },
  {
    slug: 'how-to-reactivate-lapsed-chiropractic-patients',
    title: 'How to Reactivate Lapsed Chiropractic Patients (Without Awkward Outreach)',
    description: 'Most chiropractic practices sit on hundreds of lapsed patients worth more than new ones. Here\'s the reactivation math — and how automated sequences bring them back.',
    metaTitle: 'How to Reactivate Lapsed Chiropractic Patients | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['chiropractic', 'patient reactivation', 'healthcare', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&auto=format&fit=crop&q=80',
    content: howToReactivateLapsedChiropracticPatients,
  },
  {
    slug: 'how-chiropractors-stop-missing-new-patient-calls',
    title: 'How Chiropractors Stop Losing New Patients to Unanswered Calls',
    description: 'A new patient who gets voicemail doesn\'t leave a message — they call the next practice. Here\'s how automated missed-call follow-up keeps those leads alive.',
    metaTitle: 'How Chiropractors Stop Missing New Patient Calls | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['chiropractic', 'missed calls', 'healthcare', 'automation', 'lead generation'],
    featuredImage: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=1200&auto=format&fit=crop&q=80',
    content: howChiropractorsStopMissingNewPatientCalls,
  },
  {
    slug: 'how-to-reactivate-lapsed-dental-patients',
    title: 'How Dental Practices Are Filling Schedules With Patients They Already Have',
    description: 'Dental practices lose 20–30% of active patients to silent attrition yearly. Here\'s why recall postcards fail and what automated text reactivation looks like.',
    metaTitle: 'How to Reactivate Lapsed Dental Patients | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['dental', 'patient reactivation', 'healthcare', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=1200&auto=format&fit=crop&q=80',
    content: howToReactivateLapsedDentalPatients,
  },
  {
    slug: 'dental-appointment-reminders-reduce-no-shows',
    title: 'How Dental Practices Cut No-Shows With Automated Appointment Reminders',
    description: 'Dental no-shows cost practices $30k–$80k a year. Here\'s how a multi-touch automated reminder sequence — text, email, reschedule — cuts empty chairs.',
    metaTitle: 'How to Reduce Dental No-Shows | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['dental', 'no-shows', 'healthcare', 'automation', 'appointment reminders'],
    featuredImage: 'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?w=1200&auto=format&fit=crop&q=80',
    content: dentalAppointmentRemindersReduceNoShows,
  },
  {
    slug: 'how-to-reactivate-lapsed-med-spa-clients',
    title: 'How Med Spas Are Bringing Back Clients Who Stopped Booking',
    description: 'Med spa clients lapse from inertia, not dissatisfaction. Here\'s how treatment-timed automated outreach wins back Botox and filler clients — without discounts.',
    metaTitle: 'How to Reactivate Lapsed Med Spa Clients | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['med spa', 'client reactivation', 'healthcare', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=1200&auto=format&fit=crop&q=80',
    content: howToReactivateLapsedMedSpaClients,
  },
  {
    slug: 'med-spa-consultation-follow-up-sequence',
    title: 'Why Most Med Spa Consultations Don\'t Convert — and What to Do About It',
    description: 'Most med spa consults end with "I\'ll think about it." Practices that convert 50–60% aren\'t doing better consultations — they\'re doing better follow-up.',
    metaTitle: 'How Med Spas Convert More Consultations | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['med spa', 'consultation conversion', 'healthcare', 'automation', 'follow-up'],
    featuredImage: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=1200&auto=format&fit=crop&q=80',
    content: medSpaConsultationFollowUpSequence,
  },
  {
    slug: 'how-to-reactivate-lapsed-physical-therapy-patients',
    title: 'How Physical Therapy Practices Win Back Patients Who Discharged Early',
    description: 'PT practices lose revenue twice — from early discharge and patients who don\'t return when pain recurs. Here\'s how a 30/60/90-day automated check-in changes that.',
    metaTitle: 'Reactivate Lapsed Physical Therapy Patients | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['physical therapy', 'patient reactivation', 'healthcare', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&auto=format&fit=crop&q=80',
    content: howToReactivateLapsedPhysicalTherapyPatients,
  },
  {
    slug: 'how-physical-therapy-practices-improve-patient-adherence',
    title: 'How Physical Therapy Practices Stop Losing Patients Mid Plan-of-Care',
    description: 'PT patients drop off at visit five of twelve because nobody stays in contact between sessions. Here\'s how automated check-ins reduce drop-off and recover revenue.',
    metaTitle: 'How PT Practices Improve Patient Adherence | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-18',
    tags: ['physical therapy', 'patient adherence', 'healthcare', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1573879541250-58ae8b322b40?w=1200&auto=format&fit=crop&q=80',
    content: howPhysicalTherapyPracticesImprovePatientAdherence,
  },
  {
    slug: 'how-chiropractors-get-more-google-reviews',
    title: 'How Chiropractors Build a Google Review Presence That Wins New Patients',
    description: 'Most chiropractic practices have a gap between the care they deliver and the reviews they have. Here\'s how automated review generation closes it — timing matters.',
    metaTitle: 'How Chiropractors Get More Google Reviews | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-19',
    tags: ['chiropractic', 'google reviews', 'reputation management', 'healthcare', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?w=1200&auto=format&fit=crop&q=80',
    content: howChiropractorsGetMoreGoogleReviews,
  },
  {
    slug: 'how-dental-practices-capture-more-new-patient-leads',
    title: 'How Dental Practices Stop Losing New Patient Leads to Unanswered Calls',
    description: 'Dental practices spend real money driving new patient inquiries, then lose a share to missed calls and slow follow-up. Here\'s how automated lead capture helps.',
    metaTitle: 'Dental Practices: Capture New Patient Leads | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-19',
    tags: ['dental', 'missed calls', 'lead generation', 'healthcare', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1609207807107-5c9d96cacc08?w=1200&auto=format&fit=crop&q=80',
    content: howDentalPracticesCaptureMoreNewPatientLeads,
  },
  {
    slug: 'how-med-spas-get-more-google-reviews',
    title: 'How Med Spas Build a Review Presence That Converts Prospective Clients',
    description: 'Med spa clients often love their results but never write a review. Here\'s why timing and automation are all that stand between happy clients and a top reputation.',
    metaTitle: 'How Med Spas Get More Google Reviews | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-19',
    tags: ['med spa', 'google reviews', 'reputation management', 'healthcare', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=1200&auto=format&fit=crop&q=80',
    content: howMedSpasGetMoreGoogleReviews,
  },
  {
    slug: 'how-physical-therapy-practices-capture-new-patient-calls',
    title: 'How Physical Therapy Practices Stop Losing New Patients to Unanswered Calls',
    description: 'Direct-access PT patients are impatient — voicemail means they book elsewhere within minutes. Here\'s how automated missed-call follow-up captures those calls.',
    metaTitle: 'How PT Practices Capture New Patient Calls | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-19',
    tags: ['physical therapy', 'missed calls', 'lead generation', 'healthcare', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=1200&auto=format&fit=crop&q=80',
    content: howPhysicalTherapyPracticesCaptureNewPatientCalls,
  },
  {
    slug: 'how-dental-practices-fill-hygiene-schedule-gaps',
    title: 'How Dental Practices Fill Hygiene Schedule Gaps With Automated Recall',
    description: 'Every dental practice has a backlog of overdue hygiene patients who never rebooked. Here\'s how automated recall sequences turn that list into filled appointments.',
    metaTitle: 'How Dental Practices Fill Hygiene Schedule Gaps | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-25',
    tags: ['dental', 'patient recall', 'hygiene schedule', 'healthcare', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=1200&auto=format&fit=crop&q=80',
    content: howDentalPracticesFillHygieneScheduleGaps,
  },
  {
    slug: 'how-med-spas-capture-after-hours-leads',
    title: 'How Med Spas Capture After-Hours Leads Before Competitors Do',
    description: 'Most med spa inquiries arrive after 7 PM when no one is watching the inbox. Here\'s why after-hours lead response is the highest-leverage system a practice can add.',
    metaTitle: 'How Med Spas Capture After-Hours Leads | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-25',
    tags: ['med spa', 'lead generation', 'after-hours', 'healthcare', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=1200&auto=format&fit=crop&q=80',
    content: howMedSpasCaptureAfterHoursLeads,
  },
  {
    slug: 'how-chiropractic-practices-reduce-cancellations',
    title: 'How Chiropractic Practices Reduce Cancellations and No-Shows With Automated Reminders',
    description: 'Cancellations and no-shows are both a revenue and a retention problem. Here\'s how automated reminders and post-cancellation follow-up keep patients on plan.',
    metaTitle: 'How Chiropractors Reduce Cancellations | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-25',
    tags: ['chiropractic', 'cancellations', 'no-shows', 'healthcare', 'automation'],
    featuredImage: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=1200&auto=format&fit=crop&q=80',
    content: howChiropracticPracticesReduceCancellations,
  },
  {
    slug: 'how-physical-therapy-practices-increase-physician-referrals',
    title: 'How Physical Therapy Practices Increase Physician Referrals Through Better Communication',
    description: 'Physicians refer to the PT practices that keep them informed. Here\'s how systematized progress notes, milestone updates, and discharge summaries build referrals.',
    metaTitle: 'How PT Practices Grow Physician Referrals | Wayne AI',
    author: 'Wayne AI',
    date: '2026-04-25',
    tags: ['physical therapy', 'physician referrals', 'healthcare', 'automation', 'communication'],
    featuredImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&auto=format&fit=crop&q=80',
    content: howPhysicalTherapyPracticesIncreasePhysicianReferrals,
  },
];
